sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    php: 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [[ $(phpenv version-name) == '5.6' ]]; then composer require satooshi/php-coveralls:dev-master -n ; fi
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - if [[ $(phpenv version-name) == '5.6' ]]; then phpunit --coverage-clover build/logs/clover.xml ; fi
  - if [[ $(phpenv version-name) != '5.6' ]]; then phpunit ; fi

after_success:
  - if [[ $(phpenv version-name) == '5.6' ]]; then php vendor/bin/coveralls -v ; fi
